application: hello-gapi-68d5fbf48bdd5390d94
version: 1
runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /.*
  script: main.app

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
